### ISSUE TITLE
Having trouble with V1.1.0 and V2.0 beta

### ISSUE THREAD

**Issue by manikandan0682** [Zecat/paper-stepper#20] opened 2016-07-23 03:40 UTC
Hello,

We are trying to use this stepper control for one of our requirement. When we use V1.1.0 , it is starting the steps with 0 index and complete styling is not working fine. so we tried using different versions of control, V2.0 beta is not even rendering the controls in chrome but the same works in Edge. Appreciating your response.

Thanks,
Mani

**Comment by Zecat** [comment] 2016-08-04 19:02
Hi, your problem is certainly a duplicate of #12, for now, the element doesn't work with shadow DOM.

**Comment by sowsan** [comment] 2016-08-04 20:12
Saw that there is a fork on this project and commented as its fixed. @Zecat any idea when its going to be fixed ? As soon as I use the below code all styles / animations and features are missing.

 window.performance && performance.mark && performance.mark('index.html');

```
Polymer = {lazyRegister: true, dom: 'shadow'};

(function() {
  if ('registerElement' in document
      && 'import' in document.createElement('link')
      && 'content' in document.createElement('template')) {
    // platform is good!
  } else {
    // polyfill the platform!
    var e = document.createElement('script');
    e.src = '/bower_components/webcomponentsjs/webcomponents-lite.min.js';
    document.body.appendChild(e);
  }
})();
```

**Comment by Zecat** [comment] 2016-08-04 20:30
Yep, `Polymer = {lazyRegister: true, dom: 'shadow'};` activates the shadow dom and result to #12. I work on it tonight, fixed as soon as possible!

**Comment by sowsan** [comment] 2016-08-05 00:55
Awesome thank you so much @Zecat . Truly a needed element which was missing in polymer. Thanks again for your effort on building this !

**Comment by Zecat** [comment] 2016-08-07 23:31
Hey @manikandan0682 can you please tell me if everything is alright with 2.0-beta.2?

**Comment by sowsan** [comment] 2016-08-08 18:39
@Zecat  I have tested it and it look like the rendering works fine with Shadow Dom. But seeing, few diff like label for papter-step is not displaying , once we complete a step its not getting greyed out. Thanks again for your quick work-around.

**Comment by Zecat** [comment] 2016-08-08 18:48
@sowsan Could you open a new issue with a screenshot and more details of your problem?

**Comment by sowsan** [comment] 2016-08-08 18:49
sure @Zecat  , thank you !

**Comment by sowsan** [comment] 2016-08-08 18:53
@Zecat  created issue #38

**Comment by sowsan** [comment] 2016-08-08 19:08
one more created separately #39

**Closed as completed** 2017-01-09 02:02 UTC
Labels: pending response
